export const WorkerConfig = {
  PREFETCH_COUNT: 1,
  MAX_RETRIES: 3,
  NACK_RETRY_DELAY_MS: 5_000,
  LOCK_TTL_SECONDS: 300,

  RATE_LIMIT_DELAY_MS: 1_000,

  BATCH_SIZE: 50,
  AVG_SUBSCRIBERS_PER_REPO: 10,
  MAX_TIME_PER_REPO_SEC: 2,
  MAX_TIME_PER_EMAIL_SEC: 1,
  SAFETY_BUFFER_SEC: 30,
} as const;
