export enum SagaState {
  STARTED = 'STARTED',
  AWAITING_EMAIL = 'AWAITING_EMAIL',
  COMPLETED = 'COMPLETED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
}

export const SUBSCRIBE_SAGA_TYPE = 'SUBSCRIBE';

export const CONFIRMATION_TIMEOUT_MS = 120_000;
